/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hndit2
 */
public class adminDashboard extends javax.swing.JFrame {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form adminDashboard
     */
    public adminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addFood_btn = new javax.swing.JButton();
        view_food = new javax.swing.JButton();
        dltFood_btn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Admin Dashboard");

        addFood_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addFood_btn.setText("Add Food");
        addFood_btn.setName(""); // NOI18N
        addFood_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFood_btnActionPerformed(evt);
            }
        });

        view_food.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        view_food.setText("View Foods");
        view_food.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_foodActionPerformed(evt);
            }
        });

        dltFood_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dltFood_btn.setText("Delete Food");
        dltFood_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltFood_btnActionPerformed(evt);
            }
        });

        updateBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updateBtn.setText("Update Foods");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(view_food, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addFood_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dltFood_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateBtn))))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addComponent(addFood_btn)
                .addGap(40, 40, 40)
                .addComponent(view_food)
                .addGap(34, 34, 34)
                .addComponent(dltFood_btn)
                .addGap(39, 39, 39)
                .addComponent(updateBtn)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFood_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFood_btnActionPerformed
        // TODO add your handling code here:
        addFood af = new addFood();
        af.show();
        dispose();
    }//GEN-LAST:event_addFood_btnActionPerformed

    private void dltFood_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltFood_btnActionPerformed
        // TODO add your handling code here:
        deleteFood df = new deleteFood();
        df.show();
        dispose();
    }//GEN-LAST:event_dltFood_btnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        updateFood uf = new updateFood();
        uf.show();
        dispose();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void view_foodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_foodActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();

        // Add columns to the model
        model.addColumn("Food ID");
        model.addColumn("Name");
        model.addColumn("Price");
        model.addColumn("Description");

        con = DbConnection.ConnectDB();
        String sql = "SELECT * FROM food";
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                String id = rs.getString("id");
                String name = rs.getString("name");
                String price = rs.getString("price");
                String description = rs.getString("description");

                model.addRow(new Object[]{id, name, price, description});
            }

 
            JTable table = new JTable(model);

            JScrollPane scrollPane = new JScrollPane(table);
            table.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

            JOptionPane.showMessageDialog(this, scrollPane, "Food Details", JOptionPane.INFORMATION_MESSAGE);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error Retrieving Data: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_view_foodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFood_btn;
    private javax.swing.JButton dltFood_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton view_food;
    // End of variables declaration//GEN-END:variables
}
